"'Product Index Screen' As screen.'autoLayout_HeaderFooter_ver1.0'":

    IndexPageContainer As groupContainer.verticalAutoLayoutContainer:
        Fill: =RGBA(122, 191, 255, 1)
        Height: =Parent.Height
        LayoutAlignItems: =LayoutAlignItems.Stretch
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        HeaderContainer As groupContainer.horizontalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =RGBA(214, 221, 224, 1)
            FillPortions: =0
            Height: =75
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            RadiusBottomLeft: =8
            RadiusBottomRight: =8
            RadiusTopLeft: =8
            RadiusTopRight: =8
            Width: =Parent.Width
            ZIndex: =2

            HeaderLogo As image:
                Height: =Parent.Height
                Image: =CD_Logo
                ZIndex: =1

            HeaderText As label:
                FillPortions: =1
                FontWeight: =FontWeight.Bold
                Height: =Parent.Height
                PaddingLeft: =15
                Size: =24
                Text: ="C&D Plastics Cold Form Setup Tool"
                ZIndex: =2

        ProductsContainer As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =RGBA(40, 134, 222, 1)
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            RadiusBottomLeft: =8
            RadiusBottomRight: =8
            RadiusTopLeft: =8
            RadiusTopRight: =8
            ZIndex: =3

            ProductSearchInput As text:
                Clear: =true
                Default: =""
                HintText: ="Search Products..."
                OnChange: =
                Width: =Parent.Width
                ZIndex: =1

            "ProductsGallery As gallery.'BrowseLayout_Vertical_TwoTextOneImageTwoColumnVariant_ver5.0'":
                AlignInContainer: =AlignInContainer.SetByContainer
                DelayItemLoading: =true
                Fill: =RGBA(122, 191, 255, 1)
                Items: =Search(Products, ProductSearchInput.Text, "cr33a_prodname")
                Layout: =Layout.Vertical
                LayoutMinHeight: =287
                LayoutMinWidth: =320
                LoadingSpinner: =LoadingSpinner.Data
                OnSelect: =
                TemplatePadding: =0
                TemplateSize: =Min(375, Self.Height - 60)
                Width: =ProductsContainer.Width
                WrapCount: =3
                ZIndex: =2

                ProductTitle As label:
                    Align: =Align.Center
                    FontWeight: =FontWeight.Semibold
                    Height: =Self.Size * 1.8
                    OnSelect: =Set(selected_product, ThisItem); Navigate('Product Show Screen', ScreenTransition.CoverRight)
                    PaddingBottom: =0
                    PaddingLeft: =0
                    PaddingRight: =0
                    PaddingTop: =0
                    Size: =18
                    Text: =ThisItem.prodName
                    VerticalAlign: =VerticalAlign.Top
                    Width: =Parent.TemplateWidth - 64
                    X: =32
                    Y: =264
                    ZIndex: =2

                ProductImage As image:
                    BorderThickness: =1
                    Height: =200
                    Image: =ThisItem.prodImg
                    ImagePosition: =ImagePosition.Stretch
                    OnSelect: =Select(ProductTitle)
                    Width: =200
                    X: =28
                    Y: =50
                    ZIndex: =3

                CustomerName As label:
                    Align: =Align.Center
                    OnSelect: =Select(Parent)
                    Size: =12
                    Text: =ThisItem.Customer.custName
                    X: =53
                    Y: =296
                    ZIndex: =4

        FooterContainer As groupContainer.horizontalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =RGBA(214, 221, 224, 1)
            FillPortions: =0
            Height: =75
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            RadiusBottomLeft: =8
            RadiusBottomRight: =8
            RadiusTopLeft: =8
            RadiusTopRight: =8
            ZIndex: =4

            NewProductButton As button:
                Align: =Align.Right
                BorderColor: =RGBA(0, 0, 0, 0)
                Color: =RGBA(72, 163, 62, 1)
                Fill: =RGBA(0, 0, 0, 0)
                FontWeight: =FontWeight.Bold
                Height: =Parent.Height
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =15
                PaddingTop: =0
                Size: =20
                Text: ="+ Add New Product"
                Width: =275
                ZIndex: =1

