"'Product Show Screen' As screen.'autoLayout_HeaderFooter_ver1.0'":

    IndexPageContainer_1 As groupContainer.verticalAutoLayoutContainer:
        Fill: =RGBA(122, 191, 255, 1)
        Height: =Parent.Height
        LayoutAlignItems: =LayoutAlignItems.Stretch
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        HeaderContainer_1 As groupContainer.horizontalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =RGBA(214, 221, 224, 1)
            FillPortions: =0
            Height: =75
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            RadiusBottomLeft: =8
            RadiusBottomRight: =8
            RadiusTopLeft: =8
            RadiusTopRight: =8
            Width: =Parent.Width
            ZIndex: =2

            HeaderLogo_1 As image:
                Height: =Parent.Height
                Image: =CD_Logo
                ZIndex: =1

            HeaderText_1 As label:
                FillPortions: =1
                FontWeight: =FontWeight.Bold
                Height: =Parent.Height
                PaddingLeft: =15
                Size: =24
                Text: ="C&D Plastics Cold Form Setup Tool"
                ZIndex: =2

        ProductsContainer_1 As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =RGBA(40, 134, 222, 1)
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            RadiusBottomLeft: =8
            RadiusBottomRight: =8
            RadiusTopLeft: =8
            RadiusTopRight: =8
            ZIndex: =3

            "Gallery1 As gallery.'BrowseLayout_Vertical_TwoTextOneImageVariant_ver5.0'":
                DelayItemLoading: =true
                Items: =Filter(Steps, Product.prodName = selected_product.prodName)
                Layout: =Layout.Vertical
                LayoutMinHeight: =287
                LayoutMinWidth: =320
                LoadingSpinner: =LoadingSpinner.Data
                TemplatePadding: =0
                TemplateSize: =104
                ZIndex: =1

                Image1 As image:
                    Height: =72
                    Image: =ThisItem.img0
                    OnSelect: =Select(Parent)
                    RadiusBottomLeft: =8
                    RadiusBottomRight: =8
                    RadiusTopLeft: =8
                    RadiusTopRight: =8
                    Width: =72
                    X: =16
                    Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
                    ZIndex: =1

                Title1 As label:
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =Self.Size * 1.8
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0
                    PaddingLeft: =0
                    PaddingRight: =0
                    PaddingTop: =0
                    Text: =ThisItem.setupName
                    VerticalAlign: =VerticalAlign.Top
                    Width: =Parent.TemplateWidth - 173
                    X: =103
                    Y: =(Parent.TemplateHeight - (Self.Size * 1.8 + Subtitle1.Size * 1.8)) / 2
                    ZIndex: =2

                Subtitle1 As label:
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =23
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0
                    PaddingLeft: =0
                    PaddingRight: =0
                    PaddingTop: =0
                    Text: =ThisItem.Backstop
                    VerticalAlign: =VerticalAlign.Top
                    Width: =58
                    X: =248
                    Y: =30
                    ZIndex: =3

                NextArrow1 As icon.ChevronRight:
                    AccessibleLabel: =Self.Tooltip
                    Color: =RGBA(166, 166, 166, 1)
                    Height: =50
                    Icon: =Icon.ChevronRight
                    OnSelect: =Select(Parent)
                    PaddingBottom: =16
                    PaddingLeft: =16
                    PaddingRight: =16
                    PaddingTop: =16
                    Tooltip: ="View item details"
                    Width: =50
                    X: =Parent.TemplateWidth - Self.Width - 12
                    Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
                    ZIndex: =4

                Separator1 As rectangle:
                    Height: =8
                    OnSelect: =Select(Parent)
                    Width: =Parent.TemplateWidth
                    Y: =Parent.TemplateHeight - Self.Height
                    ZIndex: =5

                Rectangle1 As rectangle:
                    Height: =Parent.TemplateHeight - Separator1.Height
                    OnSelect: =Select(Parent)
                    Visible: =ThisItem.IsSelected
                    Width: =4
                    ZIndex: =6

                Subtitle1_1 As label:
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =23
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0
                    PaddingLeft: =0
                    PaddingRight: =0
                    PaddingTop: =0
                    Text: =ThisItem.BendTarget
                    VerticalAlign: =VerticalAlign.Top
                    Width: =58
                    X: =466
                    Y: =30
                    ZIndex: =7

                Subtitle1_2 As label:
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =23
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0
                    PaddingLeft: =0
                    PaddingRight: =0
                    PaddingTop: =0
                    Text: =ThisItem.'Bend Width'
                    VerticalAlign: =VerticalAlign.Top
                    Width: =58
                    X: =357
                    Y: =30
                    ZIndex: =8

                Image1_1 As image:
                    Height: =72
                    Image: =ThisItem.img1
                    OnSelect: =Select(Parent)
                    RadiusBottomLeft: =8
                    RadiusBottomRight: =8
                    RadiusTopLeft: =8
                    RadiusTopRight: =8
                    Width: =72
                    X: =565
                    Y: =12
                    ZIndex: =9

    Button1 As button:
        OnSelect: =Navigate('Product Index Screen', ScreenTransition.Cover)
        Text: ="Back"
        X: =16
        Y: =516
        ZIndex: =2

