"'Product Show Screen' As screen":

    Label1 As label:
        Height: =318
        Text: ="SAMPLE SHOW PAGE"
        X: =40
        Y: =40
        ZIndex: =1

    Button1 As button:
        OnSelect: =Navigate('Product Index Screen')
        Text: ="Button"
        X: =60
        Y: =60
        ZIndex: =2

