"'Product Index Screen' As screen.'autoLayout_HeaderFooter_ver1.0'":

    IndexPageContainer As groupContainer.verticalAutoLayoutContainer:
        Fill: =RGBA(245, 245, 245, 1)
        Height: =Parent.Height
        LayoutAlignItems: =LayoutAlignItems.Stretch
        LayoutDirection: =LayoutDirection.Vertical
        LayoutGap: =16
        LayoutMode: =LayoutMode.Auto
        PaddingBottom: =16
        PaddingLeft: =16
        PaddingRight: =16
        PaddingTop: =16
        Width: =Parent.Width
        ZIndex: =1

        HeaderContainer As groupContainer.horizontalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =RGBA(214, 221, 224, 1)
            FillPortions: =0
            Height: =75
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            RadiusBottomLeft: =8
            RadiusBottomRight: =8
            RadiusTopLeft: =8
            RadiusTopRight: =8
            ZIndex: =2

        ProductsContainer As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =RGBA(40, 134, 222, 1)
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            RadiusBottomLeft: =8
            RadiusBottomRight: =8
            RadiusTopLeft: =8
            RadiusTopRight: =8
            ZIndex: =3

            "ProductsGallery As gallery.'BrowseLayout_Vertical_TwoTextOneImageTwoColumnVariant_ver5.0'":
                AlignInContainer: =AlignInContainer.SetByContainer
                DelayItemLoading: =true
                Fill: =RGBA(71, 158, 245, 1)
                Items: =Products
                Layout: =Layout.Vertical
                LoadingSpinner: =LoadingSpinner.Data
                TemplatePadding: =0
                TemplateSize: =Min(416, Self.Height - 60)
                Width: =ProductsContainer.Width
                WrapCount: =3
                ZIndex: =1

                ProductImg As image:
                    Height: =Min(Self.Width, Parent.TemplateHeight - 115)
                    ImagePosition: =ImagePosition.Fill
                    OnSelect: =Select(Parent)
                    RadiusBottomLeft: =8
                    RadiusBottomRight: =8
                    RadiusTopLeft: =8
                    RadiusTopRight: =8
                    Width: =Parent.TemplateWidth - 32
                    X: =16
                    Y: =16
                    ZIndex: =1

                ProductTitle As label:
                    Align: =Align.Center
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =Self.Size * 1.8
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0
                    PaddingLeft: =0
                    PaddingRight: =0
                    PaddingTop: =0
                    Size: =18
                    Text: =ThisItem.Product
                    VerticalAlign: =VerticalAlign.Top
                    Width: =Parent.TemplateWidth - 64
                    X: =32
                    Y: =ProductImg.Y + ProductImg.Height + 16
                    ZIndex: =2

        FooterContainer As groupContainer.horizontalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =RGBA(214, 221, 224, 1)
            FillPortions: =0
            Height: =75
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            RadiusBottomLeft: =8
            RadiusBottomRight: =8
            RadiusTopLeft: =8
            RadiusTopRight: =8
            ZIndex: =4

