"'Product Show Screen' As screen.'autoLayout_HeaderFooter_ver1.0'":

    IndexPageContainer_1 As groupContainer.verticalAutoLayoutContainer:
        Fill: =RGBA(122, 191, 255, 1)
        Height: =266.80
        LayoutAlignItems: =LayoutAlignItems.Stretch
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        PaddingBottom: =0.00
        PaddingLeft: =0.00
        Width: =Parent.Width
        Y: =0.00
        ZIndex: =1

        HeaderContainer_1 As groupContainer.horizontalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =RGBA(214, 221, 224, 1)
            FillPortions: =0
            Height: =100.05
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingBottom: =0.00
            PaddingLeft: =0.00
            RadiusBottomLeft: =8
            RadiusBottomRight: =8
            RadiusTopLeft: =8
            RadiusTopRight: =8
            Width: =Parent.Width
            Y: =0.00
            ZIndex: =2

            HeaderLogo_1 As image:
                Height: =100.05
                Image: =CD_Logo
                PaddingBottom: =0.00
                PaddingLeft: =0.00
                Y: =0.00
                ZIndex: =1

            HeaderText_1 As label:
                FillPortions: =1
                FontWeight: =FontWeight.Bold
                Height: =100.05
                PaddingBottom: =6.67
                PaddingLeft: =20.01
                Size: =32.02
                Text: ="C&D Plastics Cold Form Setup Tool"
                Y: =0.00
                ZIndex: =2

        ProductsContainer_1 As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =RGBA(40, 134, 222, 1)
            Height: =266.80
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingBottom: =0.00
            PaddingLeft: =0.00
            RadiusBottomLeft: =8
            RadiusBottomRight: =8
            RadiusTopLeft: =8
            RadiusTopRight: =8
            Y: =0.00
            ZIndex: =3

            "Gallery1 As gallery.'BrowseLayout_Vertical_TwoTextOneImageVariant_ver5.0'":
                DelayItemLoading: =true
                Height: =767.04
                Items: =Filter(Steps, Product.prodName = selected_product.prodName)
                Layout: =Layout.Vertical
                LayoutMinHeight: =287
                LayoutMinWidth: =320
                LoadingSpinner: =LoadingSpinner.Data
                TemplatePadding: =0.00
                TemplateSize: =138.73
                Y: =0.00
                ZIndex: =1

                Image1 As image:
                    Height: =96.05
                    Image: =ThisItem.img0
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0.00
                    PaddingLeft: =0.00
                    RadiusBottomLeft: =8
                    RadiusBottomRight: =8
                    RadiusTopLeft: =8
                    RadiusTopRight: =8
                    Width: =72
                    X: =16
                    Y: =21.34
                    ZIndex: =1

                Title1 As label:
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =33.62
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0.00
                    PaddingLeft: =0.00
                    PaddingRight: =0
                    PaddingTop: =0
                    Size: =18.68
                    Text: =ThisItem.setupName
                    VerticalAlign: =VerticalAlign.Top
                    Width: =Parent.TemplateWidth - 173
                    X: =103
                    Y: =38.15
                    ZIndex: =2

                Subtitle1 As label:
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =30.68
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0.00
                    PaddingLeft: =0.00
                    PaddingRight: =0
                    PaddingTop: =0
                    Size: =16.01
                    Text: =ThisItem.Backstop
                    VerticalAlign: =VerticalAlign.Top
                    Width: =58
                    X: =248
                    Y: =40.02
                    ZIndex: =3

                NextArrow1 As icon.ChevronRight:
                    AccessibleLabel: =Self.Tooltip
                    Color: =RGBA(166, 166, 166, 1)
                    Height: =66.70
                    Icon: =Icon.ChevronRight
                    OnSelect: =Select(Parent)
                    PaddingBottom: =21.34
                    PaddingLeft: =21.34
                    PaddingRight: =16
                    PaddingTop: =16
                    Tooltip: ="View item details"
                    Width: =50
                    X: =Parent.TemplateWidth - Self.Width - 12
                    Y: =36.02
                    ZIndex: =4

                Separator1 As rectangle:
                    Height: =10.67
                    OnSelect: =Select(Parent)
                    Width: =Parent.TemplateWidth
                    Y: =128.06
                    ZIndex: =5

                Rectangle1 As rectangle:
                    Height: =128.06
                    OnSelect: =Select(Parent)
                    Visible: =ThisItem.IsSelected
                    Width: =4
                    Y: =0.00
                    ZIndex: =6

                Subtitle1_1 As label:
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =30.68
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0.00
                    PaddingLeft: =0.00
                    PaddingRight: =0
                    PaddingTop: =0
                    Size: =16.01
                    Text: =ThisItem.BendTarget
                    VerticalAlign: =VerticalAlign.Top
                    Width: =58
                    X: =466
                    Y: =40.02
                    ZIndex: =7

                Subtitle1_2 As label:
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =30.68
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0.00
                    PaddingLeft: =0.00
                    PaddingRight: =0
                    PaddingTop: =0
                    Size: =16.01
                    Text: =ThisItem.'Bend Width'
                    VerticalAlign: =VerticalAlign.Top
                    Width: =58
                    X: =357
                    Y: =40.02
                    ZIndex: =8

                Image1_1 As image:
                    Height: =96.05
                    Image: =ThisItem.img1
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0.00
                    PaddingLeft: =0.00
                    RadiusBottomLeft: =8
                    RadiusBottomRight: =8
                    RadiusTopLeft: =8
                    RadiusTopRight: =8
                    Width: =72
                    X: =565
                    Y: =16.01
                    ZIndex: =9

    Button1 As button:
        Height: =53.36
        OnSelect: =Navigate('Product Index Screen', ScreenTransition.Cover)
        PaddingBottom: =6.67
        PaddingLeft: =6.67
        Size: =20.01
        Text: ="Back"
        X: =16
        Y: =688.34
        ZIndex: =2

